/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BBadge: typeof import('bootstrap-vue-next')['BBadge']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BOverlay: typeof import('bootstrap-vue-next')['BOverlay']
    BPopover: typeof import('bootstrap-vue-next')['BPopover']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BTab: typeof import('bootstrap-vue-next')['BTab']
    BTabs: typeof import('bootstrap-vue-next')['BTabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vBModal: typeof import('bootstrap-vue-next')['vBModal']
  }
}
